# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hra_msgs/ExecuteTrajectoryAction.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import actionlib_msgs.msg
import genpy
import geometry_msgs.msg
import hra_msgs.msg
import std_msgs.msg

class ExecuteTrajectoryAction(genpy.Message):
  _md5sum = "b668c278cdb65a6c07993c993a186743"
  _type = "hra_msgs/ExecuteTrajectoryAction"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

ExecuteTrajectoryActionGoal action_goal
ExecuteTrajectoryActionResult action_result
ExecuteTrajectoryActionFeedback action_feedback

================================================================================
MSG: hra_msgs/ExecuteTrajectoryActionGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
ExecuteTrajectoryGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: hra_msgs/ExecuteTrajectoryGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# ExecuteTrajectory.action
# Action 定义：用于请求执行一条点到点轨迹

# Goal: 任务目标
geometry_msgs/Pose target_pose  # 期望的目标位姿
float64 duration              # 期望的轨迹总时长 (秒)

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: hra_msgs/ExecuteTrajectoryActionResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
ExecuteTrajectoryResult result

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text


================================================================================
MSG: hra_msgs/ExecuteTrajectoryResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Result: 任务结果
bool success                  # 任务是否成功完成

================================================================================
MSG: hra_msgs/ExecuteTrajectoryActionFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
ExecuteTrajectoryFeedback feedback

================================================================================
MSG: hra_msgs/ExecuteTrajectoryFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Feedback: 任务执行过程中的反馈
# (可以留空，或返回当前执行到的轨迹点)
TrajectoryPoint current_point

================================================================================
MSG: hra_msgs/TrajectoryPoint
# TrajectoryPoint.msg
# 包含一个时间点的完整6-DOF期望状态

# 轨迹的相对时间戳 (从0开始)
duration time_from_start

# 期望位姿 (位置 + 姿态)
geometry_msgs/Pose pose

# 期望速度 (线速度 + 角速度)
geometry_msgs/Twist velocity

# 期望加速度 (线加速度 + 角加速度)
geometry_msgs/Accel acceleration
================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3 linear
Vector3 angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['action_goal','action_result','action_feedback']
  _slot_types = ['hra_msgs/ExecuteTrajectoryActionGoal','hra_msgs/ExecuteTrajectoryActionResult','hra_msgs/ExecuteTrajectoryActionFeedback']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       action_goal,action_result,action_feedback

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ExecuteTrajectoryAction, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.action_goal is None:
        self.action_goal = hra_msgs.msg.ExecuteTrajectoryActionGoal()
      if self.action_result is None:
        self.action_result = hra_msgs.msg.ExecuteTrajectoryActionResult()
      if self.action_feedback is None:
        self.action_feedback = hra_msgs.msg.ExecuteTrajectoryActionFeedback()
    else:
      self.action_goal = hra_msgs.msg.ExecuteTrajectoryActionGoal()
      self.action_result = hra_msgs.msg.ExecuteTrajectoryActionResult()
      self.action_feedback = hra_msgs.msg.ExecuteTrajectoryActionFeedback()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs))
      _x = self.action_goal.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs))
      _x = self.action_goal.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d3I().pack(_x.action_goal.goal.target_pose.position.x, _x.action_goal.goal.target_pose.position.y, _x.action_goal.goal.target_pose.position.z, _x.action_goal.goal.target_pose.orientation.x, _x.action_goal.goal.target_pose.orientation.y, _x.action_goal.goal.target_pose.orientation.z, _x.action_goal.goal.target_pose.orientation.w, _x.action_goal.goal.duration, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs))
      _x = self.action_result.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs))
      _x = self.action_result.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_result.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_result.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.action_result.result.success, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs))
      _x = self.action_feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs))
      _x = self.action_feedback.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_feedback.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_feedback.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i19d().pack(_x.action_feedback.feedback.current_point.time_from_start.secs, _x.action_feedback.feedback.current_point.time_from_start.nsecs, _x.action_feedback.feedback.current_point.pose.position.x, _x.action_feedback.feedback.current_point.pose.position.y, _x.action_feedback.feedback.current_point.pose.position.z, _x.action_feedback.feedback.current_point.pose.orientation.x, _x.action_feedback.feedback.current_point.pose.orientation.y, _x.action_feedback.feedback.current_point.pose.orientation.z, _x.action_feedback.feedback.current_point.pose.orientation.w, _x.action_feedback.feedback.current_point.velocity.linear.x, _x.action_feedback.feedback.current_point.velocity.linear.y, _x.action_feedback.feedback.current_point.velocity.linear.z, _x.action_feedback.feedback.current_point.velocity.angular.x, _x.action_feedback.feedback.current_point.velocity.angular.y, _x.action_feedback.feedback.current_point.velocity.angular.z, _x.action_feedback.feedback.current_point.acceleration.linear.x, _x.action_feedback.feedback.current_point.acceleration.linear.y, _x.action_feedback.feedback.current_point.acceleration.linear.z, _x.action_feedback.feedback.current_point.acceleration.angular.x, _x.action_feedback.feedback.current_point.acceleration.angular.y, _x.action_feedback.feedback.current_point.acceleration.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_goal is None:
        self.action_goal = hra_msgs.msg.ExecuteTrajectoryActionGoal()
      if self.action_result is None:
        self.action_result = hra_msgs.msg.ExecuteTrajectoryActionResult()
      if self.action_feedback is None:
        self.action_feedback = hra_msgs.msg.ExecuteTrajectoryActionFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.action_goal.goal.target_pose.position.x, _x.action_goal.goal.target_pose.position.y, _x.action_goal.goal.target_pose.position.z, _x.action_goal.goal.target_pose.orientation.x, _x.action_goal.goal.target_pose.orientation.y, _x.action_goal.goal.target_pose.orientation.z, _x.action_goal.goal.target_pose.orientation.w, _x.action_goal.goal.duration, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs,) = _get_struct_8d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_result.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.text = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.action_result.result.success, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.action_result.result.success = bool(self.action_result.result.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_feedback.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.text = str[start:end]
      _x = self
      start = end
      end += 160
      (_x.action_feedback.feedback.current_point.time_from_start.secs, _x.action_feedback.feedback.current_point.time_from_start.nsecs, _x.action_feedback.feedback.current_point.pose.position.x, _x.action_feedback.feedback.current_point.pose.position.y, _x.action_feedback.feedback.current_point.pose.position.z, _x.action_feedback.feedback.current_point.pose.orientation.x, _x.action_feedback.feedback.current_point.pose.orientation.y, _x.action_feedback.feedback.current_point.pose.orientation.z, _x.action_feedback.feedback.current_point.pose.orientation.w, _x.action_feedback.feedback.current_point.velocity.linear.x, _x.action_feedback.feedback.current_point.velocity.linear.y, _x.action_feedback.feedback.current_point.velocity.linear.z, _x.action_feedback.feedback.current_point.velocity.angular.x, _x.action_feedback.feedback.current_point.velocity.angular.y, _x.action_feedback.feedback.current_point.velocity.angular.z, _x.action_feedback.feedback.current_point.acceleration.linear.x, _x.action_feedback.feedback.current_point.acceleration.linear.y, _x.action_feedback.feedback.current_point.acceleration.linear.z, _x.action_feedback.feedback.current_point.acceleration.angular.x, _x.action_feedback.feedback.current_point.acceleration.angular.y, _x.action_feedback.feedback.current_point.acceleration.angular.z,) = _get_struct_2i19d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs))
      _x = self.action_goal.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs))
      _x = self.action_goal.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d3I().pack(_x.action_goal.goal.target_pose.position.x, _x.action_goal.goal.target_pose.position.y, _x.action_goal.goal.target_pose.position.z, _x.action_goal.goal.target_pose.orientation.x, _x.action_goal.goal.target_pose.orientation.y, _x.action_goal.goal.target_pose.orientation.z, _x.action_goal.goal.target_pose.orientation.w, _x.action_goal.goal.duration, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs))
      _x = self.action_result.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs))
      _x = self.action_result.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_result.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_result.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.action_result.result.success, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs))
      _x = self.action_feedback.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs))
      _x = self.action_feedback.status.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.action_feedback.status.status
      buff.write(_get_struct_B().pack(_x))
      _x = self.action_feedback.status.text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i19d().pack(_x.action_feedback.feedback.current_point.time_from_start.secs, _x.action_feedback.feedback.current_point.time_from_start.nsecs, _x.action_feedback.feedback.current_point.pose.position.x, _x.action_feedback.feedback.current_point.pose.position.y, _x.action_feedback.feedback.current_point.pose.position.z, _x.action_feedback.feedback.current_point.pose.orientation.x, _x.action_feedback.feedback.current_point.pose.orientation.y, _x.action_feedback.feedback.current_point.pose.orientation.z, _x.action_feedback.feedback.current_point.pose.orientation.w, _x.action_feedback.feedback.current_point.velocity.linear.x, _x.action_feedback.feedback.current_point.velocity.linear.y, _x.action_feedback.feedback.current_point.velocity.linear.z, _x.action_feedback.feedback.current_point.velocity.angular.x, _x.action_feedback.feedback.current_point.velocity.angular.y, _x.action_feedback.feedback.current_point.velocity.angular.z, _x.action_feedback.feedback.current_point.acceleration.linear.x, _x.action_feedback.feedback.current_point.acceleration.linear.y, _x.action_feedback.feedback.current_point.acceleration.linear.z, _x.action_feedback.feedback.current_point.acceleration.angular.x, _x.action_feedback.feedback.current_point.acceleration.angular.y, _x.action_feedback.feedback.current_point.acceleration.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.action_goal is None:
        self.action_goal = hra_msgs.msg.ExecuteTrajectoryActionGoal()
      if self.action_result is None:
        self.action_result = hra_msgs.msg.ExecuteTrajectoryActionResult()
      if self.action_feedback is None:
        self.action_feedback = hra_msgs.msg.ExecuteTrajectoryActionFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_goal.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_goal.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 76
      (_x.action_goal.goal.target_pose.position.x, _x.action_goal.goal.target_pose.position.y, _x.action_goal.goal.target_pose.position.z, _x.action_goal.goal.target_pose.orientation.x, _x.action_goal.goal.target_pose.orientation.y, _x.action_goal.goal.target_pose.orientation.z, _x.action_goal.goal.target_pose.orientation.w, _x.action_goal.goal.duration, _x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs,) = _get_struct_8d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_result.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_result.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_result.status.text = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.action_result.result.success, _x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.action_result.result.success = bool(self.action_result.result.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_feedback.status.status,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action_feedback.status.text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.action_feedback.status.text = str[start:end]
      _x = self
      start = end
      end += 160
      (_x.action_feedback.feedback.current_point.time_from_start.secs, _x.action_feedback.feedback.current_point.time_from_start.nsecs, _x.action_feedback.feedback.current_point.pose.position.x, _x.action_feedback.feedback.current_point.pose.position.y, _x.action_feedback.feedback.current_point.pose.position.z, _x.action_feedback.feedback.current_point.pose.orientation.x, _x.action_feedback.feedback.current_point.pose.orientation.y, _x.action_feedback.feedback.current_point.pose.orientation.z, _x.action_feedback.feedback.current_point.pose.orientation.w, _x.action_feedback.feedback.current_point.velocity.linear.x, _x.action_feedback.feedback.current_point.velocity.linear.y, _x.action_feedback.feedback.current_point.velocity.linear.z, _x.action_feedback.feedback.current_point.velocity.angular.x, _x.action_feedback.feedback.current_point.velocity.angular.y, _x.action_feedback.feedback.current_point.velocity.angular.z, _x.action_feedback.feedback.current_point.acceleration.linear.x, _x.action_feedback.feedback.current_point.acceleration.linear.y, _x.action_feedback.feedback.current_point.acceleration.linear.z, _x.action_feedback.feedback.current_point.acceleration.angular.x, _x.action_feedback.feedback.current_point.acceleration.angular.y, _x.action_feedback.feedback.current_point.acceleration.angular.z,) = _get_struct_2i19d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2i19d = None
def _get_struct_2i19d():
    global _struct_2i19d
    if _struct_2i19d is None:
        _struct_2i19d = struct.Struct("<2i19d")
    return _struct_2i19d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_8d3I = None
def _get_struct_8d3I():
    global _struct_8d3I
    if _struct_8d3I is None:
        _struct_8d3I = struct.Struct("<8d3I")
    return _struct_8d3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
