# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hra_msgs/ExecuteTrajectoryFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg
import hra_msgs.msg

class ExecuteTrajectoryFeedback(genpy.Message):
  _md5sum = "17c7df59a396305c6d82377c3ae56618"
  _type = "hra_msgs/ExecuteTrajectoryFeedback"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Feedback: 任务执行过程中的反馈
# (可以留空，或返回当前执行到的轨迹点)
TrajectoryPoint current_point

================================================================================
MSG: hra_msgs/TrajectoryPoint
# TrajectoryPoint.msg
# 包含一个时间点的完整6-DOF期望状态

# 轨迹的相对时间戳 (从0开始)
duration time_from_start

# 期望位姿 (位置 + 姿态)
geometry_msgs/Pose pose

# 期望速度 (线速度 + 角速度)
geometry_msgs/Twist velocity

# 期望加速度 (线加速度 + 角加速度)
geometry_msgs/Accel acceleration
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3 linear
Vector3 angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['current_point']
  _slot_types = ['hra_msgs/TrajectoryPoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       current_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ExecuteTrajectoryFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.current_point is None:
        self.current_point = hra_msgs.msg.TrajectoryPoint()
    else:
      self.current_point = hra_msgs.msg.TrajectoryPoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i19d().pack(_x.current_point.time_from_start.secs, _x.current_point.time_from_start.nsecs, _x.current_point.pose.position.x, _x.current_point.pose.position.y, _x.current_point.pose.position.z, _x.current_point.pose.orientation.x, _x.current_point.pose.orientation.y, _x.current_point.pose.orientation.z, _x.current_point.pose.orientation.w, _x.current_point.velocity.linear.x, _x.current_point.velocity.linear.y, _x.current_point.velocity.linear.z, _x.current_point.velocity.angular.x, _x.current_point.velocity.angular.y, _x.current_point.velocity.angular.z, _x.current_point.acceleration.linear.x, _x.current_point.acceleration.linear.y, _x.current_point.acceleration.linear.z, _x.current_point.acceleration.angular.x, _x.current_point.acceleration.angular.y, _x.current_point.acceleration.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.current_point is None:
        self.current_point = hra_msgs.msg.TrajectoryPoint()
      end = 0
      _x = self
      start = end
      end += 160
      (_x.current_point.time_from_start.secs, _x.current_point.time_from_start.nsecs, _x.current_point.pose.position.x, _x.current_point.pose.position.y, _x.current_point.pose.position.z, _x.current_point.pose.orientation.x, _x.current_point.pose.orientation.y, _x.current_point.pose.orientation.z, _x.current_point.pose.orientation.w, _x.current_point.velocity.linear.x, _x.current_point.velocity.linear.y, _x.current_point.velocity.linear.z, _x.current_point.velocity.angular.x, _x.current_point.velocity.angular.y, _x.current_point.velocity.angular.z, _x.current_point.acceleration.linear.x, _x.current_point.acceleration.linear.y, _x.current_point.acceleration.linear.z, _x.current_point.acceleration.angular.x, _x.current_point.acceleration.angular.y, _x.current_point.acceleration.angular.z,) = _get_struct_2i19d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i19d().pack(_x.current_point.time_from_start.secs, _x.current_point.time_from_start.nsecs, _x.current_point.pose.position.x, _x.current_point.pose.position.y, _x.current_point.pose.position.z, _x.current_point.pose.orientation.x, _x.current_point.pose.orientation.y, _x.current_point.pose.orientation.z, _x.current_point.pose.orientation.w, _x.current_point.velocity.linear.x, _x.current_point.velocity.linear.y, _x.current_point.velocity.linear.z, _x.current_point.velocity.angular.x, _x.current_point.velocity.angular.y, _x.current_point.velocity.angular.z, _x.current_point.acceleration.linear.x, _x.current_point.acceleration.linear.y, _x.current_point.acceleration.linear.z, _x.current_point.acceleration.angular.x, _x.current_point.acceleration.angular.y, _x.current_point.acceleration.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.current_point is None:
        self.current_point = hra_msgs.msg.TrajectoryPoint()
      end = 0
      _x = self
      start = end
      end += 160
      (_x.current_point.time_from_start.secs, _x.current_point.time_from_start.nsecs, _x.current_point.pose.position.x, _x.current_point.pose.position.y, _x.current_point.pose.position.z, _x.current_point.pose.orientation.x, _x.current_point.pose.orientation.y, _x.current_point.pose.orientation.z, _x.current_point.pose.orientation.w, _x.current_point.velocity.linear.x, _x.current_point.velocity.linear.y, _x.current_point.velocity.linear.z, _x.current_point.velocity.angular.x, _x.current_point.velocity.angular.y, _x.current_point.velocity.angular.z, _x.current_point.acceleration.linear.x, _x.current_point.acceleration.linear.y, _x.current_point.acceleration.linear.z, _x.current_point.acceleration.angular.x, _x.current_point.acceleration.angular.y, _x.current_point.acceleration.angular.z,) = _get_struct_2i19d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i19d = None
def _get_struct_2i19d():
    global _struct_2i19d
    if _struct_2i19d is None:
        _struct_2i19d = struct.Struct("<2i19d")
    return _struct_2i19d
