// Generated by gencpp from file hra_msgs/ExecuteTrajectoryResult.msg
// DO NOT EDIT!


#ifndef HRA_MSGS_MESSAGE_EXECUTETRAJECTORYRESULT_H
#define HRA_MSGS_MESSAGE_EXECUTETRAJECTORYRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hra_msgs
{
template <class ContainerAllocator>
struct ExecuteTrajectoryResult_
{
  typedef ExecuteTrajectoryResult_<ContainerAllocator> Type;

  ExecuteTrajectoryResult_()
    : success(false)  {
    }
  ExecuteTrajectoryResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteTrajectoryResult_

typedef ::hra_msgs::ExecuteTrajectoryResult_<std::allocator<void> > ExecuteTrajectoryResult;

typedef boost::shared_ptr< ::hra_msgs::ExecuteTrajectoryResult > ExecuteTrajectoryResultPtr;
typedef boost::shared_ptr< ::hra_msgs::ExecuteTrajectoryResult const> ExecuteTrajectoryResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator1> & lhs, const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator1> & lhs, const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hra_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hra_msgs/ExecuteTrajectoryResult";
  }

  static const char* value(const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result: 任务结果\n"
"bool success                  # 任务是否成功完成\n"
;
  }

  static const char* value(const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteTrajectoryResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hra_msgs::ExecuteTrajectoryResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRA_MSGS_MESSAGE_EXECUTETRAJECTORYRESULT_H
