// Auto-generated. Do not edit!

// (in-package hra_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let TrajectoryPoint = require('./TrajectoryPoint.js');

//-----------------------------------------------------------

class ExecuteTrajectoryFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_point = null;
    }
    else {
      if (initObj.hasOwnProperty('current_point')) {
        this.current_point = initObj.current_point
      }
      else {
        this.current_point = new TrajectoryPoint();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExecuteTrajectoryFeedback
    // Serialize message field [current_point]
    bufferOffset = TrajectoryPoint.serialize(obj.current_point, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExecuteTrajectoryFeedback
    let len;
    let data = new ExecuteTrajectoryFeedback(null);
    // Deserialize message field [current_point]
    data.current_point = TrajectoryPoint.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 160;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hra_msgs/ExecuteTrajectoryFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '17c7df59a396305c6d82377c3ae56618';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback: 任务执行过程中的反馈
    # (可以留空，或返回当前执行到的轨迹点)
    TrajectoryPoint current_point
    
    ================================================================================
    MSG: hra_msgs/TrajectoryPoint
    # TrajectoryPoint.msg
    # 包含一个时间点的完整6-DOF期望状态
    
    # 轨迹的相对时间戳 (从0开始)
    duration time_from_start
    
    # 期望位姿 (位置 + 姿态)
    geometry_msgs/Pose pose
    
    # 期望速度 (线速度 + 角速度)
    geometry_msgs/Twist velocity
    
    # 期望加速度 (线加速度 + 角加速度)
    geometry_msgs/Accel acceleration
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: geometry_msgs/Twist
    # This expresses velocity in free space broken into its linear and angular parts.
    Vector3 linear
    Vector3 angular
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    ================================================================================
    MSG: geometry_msgs/Accel
    # This expresses acceleration in free space broken into its linear and angular parts.
    Vector3  linear
    Vector3  angular
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExecuteTrajectoryFeedback(null);
    if (msg.current_point !== undefined) {
      resolved.current_point = TrajectoryPoint.Resolve(msg.current_point)
    }
    else {
      resolved.current_point = new TrajectoryPoint()
    }

    return resolved;
    }
};

module.exports = ExecuteTrajectoryFeedback;
